### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by body20002** [emmanueltouzery/decisive.nvim#3]
![image](https://github.com/emmanueltouzery/decisive.nvim/assets/33910565/0a4c23ed-8e30-4fdb-b623-244796c5723f)

NVIM: v0.9.5
Plugin Manager: Lazy
OS: nixos
plugin config:
```lua
return {
  "emmanueltouzery/decisive.nvim",
  config = function()
    require('decisive').setup{}
  end,
  lazy=true,
  ft = {'csv'},
  keys = {
    { '<leader>cca', ":lua require('decisive').align_csv({})<cr>",       { silent = true }, desc = "Align CSV",          mode = 'n' },
    { '<leader>ccA', ":lua require('decisive').align_csv_clear({})<cr>", { silent = true }, desc = "Align CSV clear",    mode = 'n' },
    { '[c', ":lua require('decisive').align_csv_prev_col()<cr>",         { silent = true }, desc = "Align CSV prev col", mode = 'n' },
    { ']c', ":lua require('decisive').align_csv_next_col()<cr>",         { silent = true }, desc = "Align CSV next col", mode = 'n' },
  }
}
```

**Comment by emmanueltouzery** [comment]
This plugin requires neovim 0.10, as only that version allows to add virtual text in the middle of the line.
If you upgrade to 0.10 it will work!

**Comment by emmanueltouzery** [comment]
PS: if you make it work, I'd welcome a PR to give the exact setup for lazy in the readme as I see you already did most of the work! 
(I'm still using packer myself)

**Comment by body20002** [comment]
upgrading to v0.10 made it work
